//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleship_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameShipConfigurations
    {
        public int ID { get; set; }
        public string PlayerFK { get; set; }
        public int GameFk { get; set; }
        public string Coordinate { get; set; }
        public int ShipFK { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Players Players { get; set; }
        public virtual Ships Ships { get; set; }
    }
}
